name = "TKLTEST_CONFIG_FILE"

# general options
[general]
    app_name = "HorspoolSearch"
    monolith_app_path = ["/workspace1/compsci621/tests/target/classes"] 
    app_classpath_file = "/workspace1/compsci621/projectMonoClasspaths.txt"
    test_directory = "/workspace1/compsci621/tackletest-tests/HorspoolSearch"
    # JDK home directory
    java_jdk_home = "/usr/lib/jvm/java-8-openjdk-amd64"
    offline_instrumentation = true
    # build_type = "maven"

# options for "tkltest generate" command
[generate]
    # time_limit = 60
    add_assertions = true # false
    # jee_support = false
    # partitions file path. If specified, this option overrides target_class_list option.
    # partitions_file = "test/data/irs/refactored/PartitionsFile.json"
    # app_build_files = ['/workspace1/compsci621/tests/pom.xml']
    # list of target classes for test generation. If unspecified, targets all application classes
    target_class_list = []
	#excluded_class_list = ["irs.Employer"]

# options for "tkltest generate randoop" command
[generate.randoop]
    no_error_revealing_tests=true

# options for "tkltest generate evosuite" command
[generate.evosuite]
    criterion = ["LINE", "BRANCH", "EXCEPTION", "WEAKMUTATION", "OUTPUT", "METHOD", "METHODNOEXCEPTION", "CBRANCH"]

# options for "tkltest generate ctd-amplified" command
[generate.ctd_amplified]
    base_test_generator = "combined" # both Randoop and EvoSuite
    #base_test_generator = "randoop"
    #base_test_generator = "evosuite"
#     refactored_app_path_prefix = "test/data/irs/refactored"
#     refactored_app_path_suffix = ["target/classes"]
    interaction_level = 1
    no_ctd_coverage = false
    num_seq_executions = 2
    augment_coverage = false    

# options for "tkltest execute" command
[execute]
    test_class = ""
    code_coverage = true
    app_packages = ["irs.*"]


[dev_tests]
    build_targets =  ['/workspace1/compsci621/coverage-reports_user-tests']
    coverage_exec_file = 'test/data/irs/user-tests/jacoco.exec'

